title: Anthony's Git Site
author: AnToine Delouche
email: acollins@qualityservice.com
description: > # this means to ignore newlines until "baseurl:"
  Just getting more experience with the GIT HUB interface

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
